### PR TITLE
[New Widgets] apAlert & apInput

### PR DESCRIPTION
**Pull request by tonipamies**
# New apAlert Widget

## Description
This is an Alert Widget.
Use it for show an alert message on your pages.

## Usage

**message**: the message to show on alert.
**style**: the style of the alert, Choice one from: alert-success, alert-info, alert-warning, alert-danger.
**isDismissible**: select true if the alert is dismissible or false if not.
**onDismiss**: if the alert is dismissible, the accion to execute when dismiss it.
**isAutoDismissible**: select true for auto-close the alert.
**timeForAutoClose**: the time in ms for auto-close the alert when isAutoDismissible is true.
**displayIcon**: select true for display an icon at left of the message.
**buttonIcon**: the name of the icon to show when displayIcon is true. (look at http://getbootstrap.com/components/ ) 
            Use the name of the Glyphicons without the prefix 'glyphicon-' for example 'ok-circle' or 'warning-sign'
			By default, if you don't put anything, an alert-success display 'ok-sign', alert-info 'info-sign', 
			alert-warning 'warning-sign' and alert-danger 'alert'
**SizeIcon**: the size of the icon, 1 to 5 being 1 normal size and 5 large size
**showcountdown**: select true to show a countdown when isAutoDismissible is true. It shows on the top-right corner. 

## Screenshot

Alert-danger sample:

alert-danger

Alert-success sample:

alert-success

### CODE REVIEW

**Comment by lio-p** [comment]
Hi,

Thanks for your contribution! 

However, I'm getting the following error while building: SyntaxError: Unexpected token x in JSON at position 3220

Do you get the same issue? I'd like to fix the issue before starting the review.

Cheers

**Comment by tonipamies** [comment]
Hi,

I have fixed it.
 It was a problem with the character set.
Now, there is no error doing the *npm run build*

Regards

**Comment by lio-p** [comment]
Thanks for the fix, I can deploy the widget now. 

Here are my feedbacks for apAlert: 
- Error after the countdown hits 0. The error message is: this.StopTimer is not a function
- When I click on the x to close the alert, the alert doesn't disappear.  
- Auto close the alert at No and Display the countdown at YES -> The countdown is still displayed. 

I would recommend to implement test for the following cases: 
- Close alert manually
- Display countdown 
- Close alert after countdown

**Comment by lio-p** [comment]
Here are my feedbacks for apInput: 

- Tooltip doesn't show up on mouse hover. Maybe there is another way to display it?
- Status icon on the right doesn't change according to the content of the input. 
- Mix of Spanish and English for the attributes, you should pick up one language.

I would advise to implement a few tests to make the widget more robust. 

As a general note, to a better adoption by fellow users, I think that pick up english as a language for the widget inputs will work better.

**Pull request closed without merging**
